<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<ApplicationIcon>Assets\ReadMD-icon.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Controls\" />
		<Folder Include="Models\" />
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>
	<ItemGroup>
		<AvaloniaResource Include="Assets\Fonts\*.ttf" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaXaml Remove="Assets\Styles.axaml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.0.3" />
		<PackageReference Include="Avalonia.Desktop" Version="12.0.3" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.3" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.3" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="MarkView.Avalonia" Version="12.0.3" />
		<PackageReference Include="FluentIcons.Avalonia" Version="2.1.326" />
		<PackageReference Include="MarkView.Avalonia.SyntaxHighlighting" Version="12.0.3" />
		<PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
		<PackageReference Include="Svg.Controls.Avalonia" Version="12.0.0.9" />
		<PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.9" />
	</ItemGroup>

	<ItemGroup>
		<AvaloniaResource Update="Assets\Styles.axaml">
			<SubType>Designer</SubType>
		</AvaloniaResource>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Views\TitleBarView.axaml.cs">
			<DependentUpon>TitleBarView.axaml</DependentUpon>
		</Compile>
	</ItemGroup>
</Project>
